version: "3.8"

services:
  #PHP Service
  php:
    build: 
      context: . # current directory
      target: php # target the php service in the dockerfile
      args:
        - APP_ENV=local
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
    working_dir: /var/www # where the app is located in the container
    volumes:
      - ./:/var/www # mount the current directory to the container directory to store the code
    ports:
      - 8000:8000 # my port so I can connect to it : docker port
    depends_on:
      - database # depends on the database service, so it needs to wait until the database is up and running

  #Database server 
  database:
    image: mysql:5.7.33
    ports:
      - 3306:3306 # my port so I can connect to it : docker port
    environment:
      MYSQL_DATABASE: realtimechatapp_docker
      MYSQL_USER: tudor
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql # where the data is stored in the container
  
  #node service
  # node:
  #   build:
  #     context: .
  #     target: node
  #   volumes:
  #     - .:/usr/src
  #     - ./node_modules:/usr/src/node_modules
  #   tty: true
  #   # command: ["npm", "run", "dev"]
  #   depends_on:
  #     - php

volumes:
  db-data: ~